# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [START cloudbuild_maven]
# added
steps:
  # Run the Maven build
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: 'bash'
    args: ['echo', 'Running Apriori MAT test -- TODO']
  - name: 'bash'
    args: ['echo', 'Running Sonar Scan -- TODO']
  - name: 'bash'
    args: ['echo', 'Parsing Sonar Result -- TODO']
  - name: 'bash'
    args: ['echo', 'Building Sonar report -- TODO']
  - name: 'bash'
    args: ['echo', 'Emailing Sonar report -- TODO']
  - name: 'bash'
    args: ['echo', 'Emailing Sonar report -- TODO']  
  # package the application  
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  # Create the docker image   
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "asia-docker.pkg.dev/hopeful-ally-360404/test/hellospring:$COMMIT_SHA", "--build-arg=JAR_FILE=target/hello-spring-1.0.0.jar", "."]
  - name: 'bash'
    args: ['echo', 'Twistcli Image Scan -- TODO'] 
  - name: 'bash'
    args: ['echo', 'Parsing Twistcli Scan results -- TODO']   
    # Push the docker image to artifact registery
  - name: gcr.io/cloud-builders/docker
    args: ["push", "asia-docker.pkg.dev/hopeful-ally-360404/test/hellospring:$COMMIT_SHA"]
  # Deploy the docker image on GKE 
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=demo-deployment.yaml
    - --image=asia-docker.pkg.dev/hopeful-ally-360404/test/hellospring:$COMMIT_SHA
    - --location=asia-east1
    - --cluster=demo-gke-deployment
  - name: 'bash'
    args: ['echo', 'Trigger MLP Dev Deployment'] 
  - name: 'bash'
    args: ['echo', 'Aposteriori Mat Test'] 
  - name: 'bash'
    args: ['echo', 'Gatling Load/Scalability Test']
  - name: 'bash'
    args: ['echo', 'Update Result'] 
  - name: 'bash'
    args: ['echo', 'Cleaning Temporary files']   
    
    
    
# [END cloudbuild_maven]
