apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "corner-demo"
  namespace: "sample-app"
  labels:
    app: "corner-demo"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "corner-demo"
  template:
    metadata:
      labels:
        app: "corner-demo"
    spec:
      containers:
      - name: "hellospring"
        image: busybox
        resources:
          limits:
            cpu: 200m
            ephemeral-storage: 10Mi
            memory: 20Mi
          requests:
            cpu: 50m
            ephemeral-storage: 10Mi
            memory: 20Mi
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "corner-demo-hpa-besk"
  namespace: "sample-app"
  labels:
    app: "corner-demo"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "corner-demo"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
